- name: Make sure snapd is installed
  apt:
    name:
      - snapd
    state: present
  become: yes
  when: ansible_distribution == 'Ubuntu'

- name: Make sure snapd is installed
  pacman:
    name:
      - snapd
    state: present
  become: yes
  when: ansible_distribution == 'Archlinux'

- name: Install microk8s
  become: yes
  snap:
    name: microk8s
    classic: yes
    channel: "{{ microk8s_version }}"

- name: Wait for microk8s to be ready
  become: yes
  command: microk8s.status --wait-ready
  changed_when: false
  register: mk8sstatusout

- name: Create kubectl alias
  become: yes
  command: "snap alias microk8s.kubectl kubectl"
  changed_when: false
  register: aliaskubectlout

- name: Create helm3 alias
  become: yes
  command: "snap alias microk8s.helm3 helm"
  changed_when: false
  register: aliashelmout
  when:
    - "'helm3' in microk8s_plugins"
    - microk8s_plugins.helm3

- name: Create custom certificates
  become: yes
  ansible.builtin.template:
    src: "{{ microk8s_csr_template }}"
    dest: /var/snap/microk8s/current/certs/csr.conf.template
    mode: 0644
  when: microk8s_csr_template is defined and microk8s_csr_template is file
  notify:
  - Refresh certs

- name: Create folder for microk8s certificates
  become: yes
  file:
    path: /usr/share/ca-certificates/extra
    state: directory
    mode: 0755

- name: Copy certificates
  become: yes
  copy:
    src: "{{ item }}"
    dest: /usr/share/ca-certificates/extra
    remote_src: yes
    force: yes
    mode: 0644
  with_fileglob:
    - /var/snap/microk8s/current/certs/*ca*.crt

- name: Trust certificates generated by microk8s
  become: yes
  command: "update-ca-certificates"
  register: command_result
  changed_when: "'0 added, 0 removed' not in command_result.stdout"

- name: Disable snap autoupdate
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: microk8s Disable snap autoupdate"
    content: |
      127.0.0.1 api.snapcraft.io
  when: microk8s_disable_snap_autoupdate

# install bitnami repo for mysql
- name: Add helm repo
  shell: "microk8s.helm3 repo add bitnami https://charts.bitnami.com/bitnami"

- name: Helm repo update bitnami
  shell: "microk8s.helm3 repo update"

- name: Helm repo for nginx controller
  shell: "microk8s.helm3  repo add nginx-stable https://helm.nginx.com/stable"

- name: Helm repo update for nginx
  shell: "microk8s.helm3 repo update"

- name: installing nginx controller with helm
  shell: "microk8s.helm3 install nginx-ingress nginx-stable/nginx-ingress"

 # install bitnami repo for mysql
- name: Add helm repo
  shell: "microk8s.helm3 install Tech-Test --set wordpressUsername=admin --set wordpressPassword=k3ns3ntm3 --set mariadb.auth.rootPassword=K3n53nTM3 --set ingress.enabled=true --set ingress.hostname=home.sargus.net.za --set memcached.enabled=true --set memcached.service.port=11211 bitnami/wordpress bitnami/wordpress" 
