#
# defaults file for ansible_role_microk8s
#

# version management
microk8s_version: "1.19/stable"
microk8s_disable_snap_autoupdate: false

# plugin configuration
microk8s_dns_resolvers: 8.8.8.8,8.8.4.4
registry_size: 20Gi
microk8s_plugins:
  dashboard: true                         # The Kubernetes dashboard
  dns: "{{ microk8s_dns_resolvers }}"     # CoreDNS
  helm3: true                             # Helm 3 - Kubernetes package manager
  host-access: true                       # Allow Pods connecting to Host services smoothly
  ingress: true                           # Ingress controller for external access
  metrics-server: true                    # K8s Metrics Server for API access to service metrics
  rbac: true                              # Role-Based Access Control for authorisation
  registry: "size={{ registry_size }}"    # Private image registry exposed on localhost:32000
  storage: true                           # Storage class; allocates storage from host directory
  ambassador: false                       # Ambassador API Gateway and Ingress
  cilium: false                           # SDN, fast with full network policy
  fluentd: false                          # Elasticsearch-Fluentd-Kibana logging and monitoring
  gpu: false                              # Automatic enablement of Nvidia CUDA
  helm: false                             # Helm 2 - the package manager for Kubernetes
  istio: false                            # Core Istio service mesh services
  jaeger: false                           # Kubernetes Jaeger operator with its simple config
  knative: false                          # The Knative framework on Kubernetes.
  kubeflow: false                         # Kubeflow for easy ML deployments
  linkerd: false                          # Linkerd is a service mesh for Kubernetes and other frameworks
  metallb: false                          # Loadbalancer for your Kubernetes cluster
  multus: false                           # Multus CNI enables attaching multiple network interfaces to pods
  prometheus: false                       # Prometheus operator for monitoring and logging
  traefik: false

helm3_repositories:
  - name: stable
    url: https://charts.helm.sh/stable

# users to make members of microk8s group
users: []

# enable high-availability?
microk8s_enable_HA: false

# hostgroup whose members will form high-availability cluster
microk8s_group_HA: "microk8s_HA"

# regex to select IP address for joining nodes in HA setup
microk8s_ip_regex_HA: "([0-9]{1,3}[\\.]){3}[0-9]{1,3}"

# for setting up custom certificate request.  Set to template name to enable
#microk8s_csr_template: null