# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
---
- name: Execute Ansible Playbook
  # You may pin to the exact commit or the version.
  # uses: saubermacherag/ansible-playbook-docker-action@6504ab82647581a928477ecb9c6d52f11fc6843f
  uses: saubermacherag/ansible-playbook-docker-action@v1.4
  with:
    # Name of the playbook in your workspace.
    playbookName: ansible/microk8s.yml
    # Name of the inventory file to use.
    inventoryFile: # ansible/host
    # Choose one of 4 verbosity levels. See Ansible documentation for details.
    verbosity: # optional
