# This is a basic workflow to help you get started with Actions

name: microk8s-create

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - name: create
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
        # Ansible playbook filepath
        playbook: microk8s.yml
        # Root directory of Ansible project (defaults to current)
        directory: ansible


